// js/data.js
const assetData = [
  { id: "A001", name: "Dell Latitude 5420", category: "Laptop", location: "Felixent HQ", status: "In Use", assignedTo: "James" },
  { id: "A002", name: "Canon LBP2900", category: "Printer", location: "Felixent Mandalay", status: "New", assignedTo: "" },
  { id: "A003", name: "Cisco Router RV340", category: "Networking", location: "Felixent HQ", status: "Maintenance", assignedTo: "IT Ops" },
  { id: "A004", name: "HP EliteBook 840", category: "Laptop", location: "Felixent Naypyidaw", status: "Reassigned", assignedTo: "Aye Chan" },
  { id: "A005", name: "Brother HL-L2320D", category: "Printer", location: "Felixent HQ", status: "Retired", assignedTo: "" },
  { id: "A006", name: "Lenovo ThinkPad X1", category: "Laptop", location: "Felixent Mandalay", status: "In Use", assignedTo: "Khin Zaw" },
  { id: "A007", name: "TP-Link TL-SG108", category: "Networking", location: "Felixent HQ", status: "New", assignedTo: "" },
  { id: "A008", name: "Epson EB-X06", category: "Projector", location: "Felixent Naypyidaw", status: "Maintenance", assignedTo: "Facilities" },
  { id: "A009", name: "Samsung Galaxy Tab A", category: "Tablet", location: "Felixent HQ", status: "In Use", assignedTo: "Hla Hla Win" },
  { id: "A010", name: "Apple MacBook Air M2", category: "Laptop", location: "Felixent Mandalay", status: "Reassigned", assignedTo: "Ko Ko" },
  { id: "A011", name: "HP LaserJet Pro M404", category: "Printer", location: "Felixent HQ", status: "Retired", assignedTo: "" },
  { id: "A012", name: "Ubiquiti UniFi AP", category: "Networking", location: "Felixent Naypyidaw", status: "In Use", assignedTo: "Network Team" },
  { id: "A013", name: "Dell OptiPlex 7090", category: "Desktop", location: "Felixent HQ", status: "New", assignedTo: "" },
  { id: "A014", name: "Logitech C920 Webcam", category: "Accessory", location: "Felixent Mandalay", status: "In Use", assignedTo: "Thandar" },
  { id: "A015", name: "Microsoft Surface Pro 7", category: "Tablet", location: "Felixent HQ", status: "Maintenance", assignedTo: "IT Ops" },
  { id: "A016", name: "Canon EOS M50", category: "Camera", location: "Felixent Naypyidaw", status: "Reassigned", assignedTo: "Media Team" },
  { id: "A017", name: "Zebra Barcode Scanner", category: "Accessory", location: "Felixent HQ", status: "Retired", assignedTo: "" },
  { id: "A018", name: "Asus ZenBook 14", category: "Laptop", location: "Felixent Mandalay", status: "In Use", assignedTo: "Nandar Htun" },
  { id: "A019", name: "Epson L3150", category: "Printer", location: "Felixent HQ", status: "New", assignedTo: "" },
  { id: "A020", name: "TP-Link Archer AX10", category: "Networking", location: "Felixent Naypyidaw", status: "Maintenance", assignedTo: "Tech Ops" },
  { id: "A021", name: "Dell UltraSharp U2723QE", category: "Monitor", location: "Felixent HQ", status: "In Use", assignedTo: "Design Team" },
  { id: "A022", name: "HP ProDesk 400 G7", category: "Desktop", location: "Felixent Mandalay", status: "Reassigned", assignedTo: "Admin Dept" },
  { id: "A023", name: "Logitech MX Master 3", category: "Accessory", location: "Felixent HQ", status: "Retired", assignedTo: "" },
  { id: "A024", name: "Samsung Galaxy S22", category: "Mobile", location: "Felixent Naypyidaw", status: "In Use", assignedTo: "Field Ops" },
  { id: "A025", name: "Apple iPad Mini 6", category: "Tablet", location: "Felixent HQ", status: "New", assignedTo: "" },
  { id: "A026", name: "Brother DCP-T520W", category: "Printer", location: "Felixent Mandalay", status: "Maintenance", assignedTo: "Support Team" },
  { id: "A027", name: "Lenovo Legion 5", category: "Laptop", location: "Felixent HQ", status: "Reassigned", assignedTo: "Dev Team" },
  { id: "A028", name: "Canon PowerShot G7X", category: "Camera", location: "Felixent Naypyidaw", status: "Retired", assignedTo: "" },
  { id: "A029", name: "TP-Link TL-WR841N", category: "Networking", location: "Felixent HQ", status: "In Use", assignedTo: "Security" },
  { id: "A030", name: "HP EliteDisplay E243", category: "Monitor", location: "Felixent Mandalay", status: "New", assignedTo: "" },
  { id: "A031", name: "Dell Precision 5560", category: "Laptop", location: "Felixent HQ", status: "Maintenance", assignedTo: "Engineering" },
  { id: "A032", name: "Samsung Galaxy A13", category: "Mobile", location: "Felixent Naypyidaw", status: "Reassigned", assignedTo: "Field Ops" },
  { id: "A033", name: "Apple Magic Keyboard", category: "Accessory", location: "Felixent HQ", status: "Retired", assignedTo: "" },
  { id: "A034", name: "HP ZBook Firefly", category: "Laptop", location: "Felixent Mandalay", status: "In Use", assignedTo: "Project Lead" },
  { id: "A035", name: "Epson EB-W06", category: "Projector", location: "Felixent HQ", status: "New", assignedTo: "" },
  { id: "A036", name: "Ubiquiti EdgeRouter X", category: "Networking", location: "Felixent Naypyidaw", status: "Maintenance", assignedTo: "Network Team" },
  { id: "A037", name: "Canon PIXMA G3020", category: "Printer", location: "Felixent HQ", status: "Reassigned", assignedTo: "Support Team" },
  { id: "A038", name: "Logitech Brio 4K", category: "Accessory", location: "Felixent Mandalay", status: "Retired", assignedTo: "" },
  { id: "A039", name: "Samsung Galaxy Tab S8", category: "Tablet", location: "Felixent HQ", status: "In Use", assignedTo: "Trainer" },
  { id: "A040", name: "Apple Mac Mini M2", category: "Desktop", location: "Felixent Naypyidaw", status: "New", assignedTo: "" },
  { id: "A041", name: "TP-Link Deco M5", category: "Networking", location: "Felixent HQ", status: "Maintenance", assignedTo: "IT Ops" },
  { id: "A042", name: "HP Envy x360", category: "Laptop", location: "Felixent Mandalay", status: "Reassigned", assignedTo: "Marketing" },
  { id: "A043", name: "Canon i-SENSYS MF445dw", category: "Printer", location: "Felixent HQ", status: "Retired", assignedTo: "" },
  { id: "A044", name: "Dell Inspiron 15", category: "Laptop", location: "Felixent Naypyidaw", status: "In Use", assignedTo: "Finance" },
  { id: "A045", name: "Epson EcoTank L3250", category: "Printer", location: "Felixent HQ", status: "New", assignedTo: "" },
  { id: "A046", name: "Ubiquiti UniFi Switch", category: "Networking", location: "Felixent Mandalay", status: "Maintenance", assignedTo: "Network Team" },
  { id: "A047", name: "Dell G15 Gaming", category: "Laptop", location: "Felixent HQ", status: "Reassigned", assignedTo: "QA Team" },
  { id: "A048", name: "Sony A6400", category: "Camera", location: "Felixent Naypyidaw", status: "In Use", assignedTo: "Content Team" },
  { id: "A049", name: "BenQ PD2700U", category: "Monitor", location: "Felixent HQ", status: "New", assignedTo: "" },
  { id: "A050", name: "Anker PowerCore 20100", category: "Accessory", location: "Felixent Mandalay", status: "In Use", assignedTo: "James" }
];
